#`npx prisma migrate dev --name create` ao subir container pela primeira vez
version: '3'

services:
  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-notes-teste:/var/lib/postgresql/data

  server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-db
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  postgres-notes-teste:
