#`npx prisma migrate dev --name create` ao subir container pela primeira vez
version: '3'

services:
  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-notes:/var/lib/postgresql/data

  app1: &app1
    hostname: app1
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-db
    expose:
      - "3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

  app2:
    <<: *app1
    hostname: app2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.25GB'
volumes:
  postgres-notes:
